name: 'sync-gitee-mirror'
description: '同步 GitHub 仓库到 Gitee 仓库'
inputs:
  repository:
    description: 'colakele/jd'
    required: true
  username:
    description: '${{ secrets.GITEEUSERNAME }}'
    required: true
  password:
    description: '${{ secrets.GITEEPASSWORD }}'
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        git init
        git remote add origin https://github.com/${GITHUB_REPOSITORY}.git
        git fetch --all
        for branch in `git branch -a | grep remotes | grep -v HEAD`; do
          git branch --track ${branch##*/} $branch
        done
      shell: bash
    - run: |
        remote_repo="https://${{ inputs.username }}:${{ inputs.password }}@gitee.com/${{ inputs.repository }}.git"
        git remote add gitee "${remote_repo}"
        git show-ref # useful for debugging
        git branch --verbose
        # publish all
        git push --all --force gitee
        git push --tags --force gitee
      shell: bash
